<?=

$this->Html->css([
    '../admin/assets/bootstrap/css/bootstrap.min',
    '../admin/assets/css/metro',
    '../admin/assets/bootstrap/css/bootstrap-responsive.min',
    '../admin/assets/bootstrap-fileupload/bootstrap-fileupload',
    '../admin/assets/font-awesome/css/font-awesome',
    '../admin/assets/css/style',
    '../admin/assets/css/style_responsive',
    '../admin/assets/css/style_default',
    '../admin/assets/gritter/css/jquery.gritter',
    '../admin/assets/chosen-bootstrap/chosen/chosen',
    '../admin/assets/jquery-tags-input/jquery.tagsinput',
    '../admin/assets/clockface/css/clockface',
    '../admin/assets/bootstrap-wysihtml5/bootstrap-wysihtml5',
    '../admin/assets/bootstrap-datepicker/css/datepicker',
    '../admin/assets/bootstrap-timepicker/compiled/timepicker',
    '../admin/assets/bootstrap-colorpicker/css/colorpicker',
    '../admin/assets/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons',
    '../admin/assets/data-tables/DT_bootstrap',
    '../admin/assets/bootstrap-daterangepicker/daterangepicker',
    '../admin/assets/uniform/css/uniform.default'
]);
?>